### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Thamjith** [thednp/kute.js#109] opened 2021-10-28 15:12 UTC
Im getting "ReferenceError: window is not defined" while using kute.js on a next.js project.

**Comment by thednp** [comment] 2021-10-30 06:35
Can we have the full error report?

**Comment by Thamjith** [comment] 2021-10-30 13:00
ReferenceError: window is not defined
    at D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:1264 
    at D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:84   
    at Object.<anonymous> (D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:199)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.kute.js (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:1406:18)
    at __webpack_require__ (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:23:31)
    at Module../pages/index.js (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:1182:65)
    at __webpack_require__ (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:23:31)
    at D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:91:18
    at Object.<anonymous> (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
ReferenceError: window is not defined
    at D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:1264 
    at D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:84   
    at Object.<anonymous> (D:\Personal Projects\PersonalWebsite\node_modules\kute.js\dist\kute.min.js:2:199)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.kute.js (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:1406:18)
    at __webpack_require__ (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:23:31)
    at Module../pages/index.js (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:1182:65)
    at __webpack_require__ (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:23:31)
    at D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:91:18
    at Object.<anonymous> (D:\Personal Projects\PersonalWebsite\.next\server\pages\index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)

**Comment by Thamjith** [comment] 2021-10-30 13:01
![image](https://user-images.githubusercontent.com/24909620/139533807-b9ac0c62-fff3-48af-a339-b9d78d8b3638.png)

**Comment by Thamjith** [comment] 2021-10-30 13:02
just create a default nextjs app and import the kutejs library. Then you will get the error.

**Comment by thednp** [comment] 2021-10-30 19:00
Can you please test the master version? I remember some of my last few commits were addressing this issue.

**Comment by thednp** [comment] 2021-11-01 11:17
@Thamjith I'm not familiar with next.js, but I think it's best to mention that KUTE.js cannot work outside the browser scope as it relies heavily on the web API. Also the library works best in a site `<footer>`, not `<head>`.

**Comment by fredericrous** [comment] 2021-11-07 14:06
I am able to reproduce the error. The reproduction workflow is straightforward:
- [Create a new nextjs app](https://nextjs.org/docs/api-reference/create-next-app)
- import kute with `import KUTE from 'kute.js'` in any component

window does not exist because NextJS tries to generate SSR. Ideally, Kute.JS should check if the `window` object exists and if it doesn't it should return silently

**Comment by thednp** [comment] 2021-11-07 14:59
I forgot to mention I am not familiar with NextJS and I may not have the time to investigate at this time, but I'm open to suggestions.

**Comment by fredericrous** [comment] 2021-11-08 00:27
that might not be a perfect solution but basically what I did to fix the issue on nextjs is to add `if (typeof window === 'undefined') return` at the first line of `dist/kute.js` 
I opened a PR as a suggestion https://github.com/thednp/kute.js/pull/110

**Comment by thednp** [comment] 2021-11-09 14:36
Thanks, I will have a look at this as soon as I can.

**Comment by thednp** [comment] 2021-11-10 15:06
@fredericrous @Thamjith please have a minute and test latest master.

Thanks

**Comment by thednp** [comment] 2021-11-11 12:19
Can anyone please confirm the fix is working somewhat?

**Comment by Thamjith** [comment] 2021-11-11 14:09
@thednp Unfortunately the error is still there. The kute,js version Im using is "^2.1.2". Another thing I observed is while importing kute.js there is a warning 

`Could not find a declaration file for module 'kute.js'. 'd:/Personal Projects/test/test/node_modules/kute.js/dist/kute.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/kute.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'kute.js';``
  
[Here](https://github.com/Thamjith/nextjskutejs) is a github link to the sample nextjs project i build for testing.

**Comment by thednp** [comment] 2021-11-11 15:11
@Thamjith did you test the master version? Try:

```
npm install thednp/kute.js#master
```

**Comment by Thamjith** [comment] 2021-11-11 17:20
@thednp ,No its still not working. Maybe its something that I have done wrong. Im new to reactjs and nextjs. If there is anyone who has experience in these libraries will help.

**Comment by thednp** [comment] 2021-11-11 18:07
We don't have TypeScript adaptation/source, perhaps this could be a problem as well?

**Comment by thednp** [comment] 2021-11-12 07:43
I'm reading the [d.ts](https://github.com/thednp/bootstrap.native/blob/master/src/index.d.ts) someone made for my `bootstrap.native` but I will need help with kute.js. Will you guys give me a hand with that?

**Comment by thednp** [comment] 2021-11-12 11:15
Guys @Thamjith @fredericrous I've set up a `tsconfig.json` and it seems to work. Now I need to know if you guys need a single file with all declarations or a complete file+folder declaration(s)?

**Comment by thednp** [comment] 2021-11-12 13:31
@Thamjith @fredericrous please test latest master

**Comment by Thamjith** [comment] 2021-11-12 14:41
I removed kute.js first and then installed the latest master using `npm install thednp/kute.js#master
` but still the error is there.

**Comment by thednp** [comment] 2021-11-12 15:41
I see, let's take it one step at a time. First, is the typescript implementation good?

**Comment by thednp** [comment] 2021-11-13 10:28
@fredericrous @itpropro @Thamjith please test latest master `npm install github:thednp/kute.js`.

Thanks.

**Comment by Thamjith** [comment] 2021-11-13 16:34
It worked.

**Comment by thednp** [comment] 2021-11-13 16:56
Please update to KUTE.js 2.1.3 and confirm :)

**Comment by Thamjith** [comment] 2021-11-13 17:43
It worked.

![image](https://user-images.githubusercontent.com/24909620/141653690-7aa178aa-1789-4e96-a421-ed09f13aa7fa.png)


You can see the package.json [here](https://github.com/Thamjith/nextjskutejs/blob/main/package.json)

[example](https://nextjskutejs.vercel.app/)

**Comment by thednp** [comment] 2021-11-13 18:15
So we can close the issue.

**Closed** 2021-11-13 19:33 UTC
Labels: enhancement, help wanted
